# Generated by Django 4.0.2 on 2022-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_chequestatus_alter_cheque_options_cheque_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequestatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cheque statuses'},
        ),
        migrations.AddField(
            model_name='cheque',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
