# Generated by Django 4.0.2 on 2022-02-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_alter_chequestatus_options_cheque_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheques.chequestatus'),
        ),
    ]
