# Generated by Django 4.0.2 on 2022-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_remove_cheque_status_cheque_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheque',
            name='is_processing',
            field=models.BooleanField(default=True),
        ),
    ]
